pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'python' }
      }
      steps {
        sh 'pip3 install -r multi-stage-multi-agent/requirements.txt'
      }
      steps{
        sh 'python3 multi-stage-multi-agent/hello.py'
      }
    }
    stage('Database'){
      agent{
        docker { image 'mysql'}
      }
      steps{
        sh 'SELECT VERSION();'
      }
  }
}
}
