pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'python' }
      }
      steps {
        sh 'python https://github.com/PavanKarthik12/Jenkins-Zero-To-Hero/blob/main/multi-stage-multi-agent/hello.py'
      }
    }
    stage('Database'){
      agent{
        docker { image 'mysql'}
      }
      steps{
        sh 'SELECT VERSION();'
      }
  }
}
}
