name: Test, Upload artifact and Deploy to Heroku

on: 
  - workflow_dispatch
  - pull_request
  - push

jobs:
  call-workflow:
    uses: PavanKarthik12/Reactjs-Project-custom-actions/.github/workflows/action.yaml@master
